server.port: 8084

spring:
  jpa:
    hibernate.ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/online_commerce_shop
    username: online-commerce-shop-admin
    password: online-commerce-shop-admin

